force-app/main/default/objects/Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>Attendee</label>
    <nameField>
        <label>Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Training_Session__c.object
<CustomObject>
    <fields>
        <fullName>Training_Topics__c</fullName>
        <label>Training Topics</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Page Layouts</fullName>
                </value>
                <value>
                    <fullName>Validation Rules</fullName>
                </value>
                <value>
                    <fullName>Record Types</fullName>
                </value>
                <value>
                    <fullName>Custom Fields</fullName>
                </value>
                <value>
                    <fullName>Apex</fullName>
                </value>
                <value>
                    <fullName>Triggers</fullName>
                </value>
                <value>
                    <fullName>Flows</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Training Session</label>
    <nameField>
        <label>Training Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Sessions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/AttendeeTriggerHandlerTest.cls
@isTest
public class AttendeeTriggerHandlerTest {
    @isTest
    static void InsertAttendeeTest(){
        
        contact con =new contact(LastName='Agarwal');
        insert con;
        
        Training_Session__c ts=new Training_Session__c(Training_Topics__c='Page Layouts',Name='Test Training',RecordTypeId='012dM000003l5FRQAY');
        insert ts;
        
        Attendee__c att=new Attendee__c(Email__c='abc@gmail.com',Training_Session__c= ts.id,Contact__c=con.Id);
        
        Test.startTest();
        insert att;
        Test.stopTest();
    }
    
    @isTest
    static void updateAttendeeTest(){
        
        contact con =new contact(LastName='Agarwal');
        insert con;
        
        contact con2 =new contact(LastName='Agarwal2');
        insert con2;
        
        Training_Session__c ts=new Training_Session__c(Training_Topics__c='Page Layouts',Name='Test Training',RecordTypeId='012dM000003l5FRQAY');
        insert ts;
        
        Attendee__c att=new Attendee__c(Email__c='abc@gmail.com',Training_Session__c= ts.id,Contact__c=con.Id);
        insert att;
        
        att.Contact__c=con2.Id;
        update att;
    }
    
    @isTest
    static void deleteAttendeeTest(){
        
        contact con =new contact(LastName='Agarwal');
        insert con;
        
        contact con2 =new contact(LastName='Agarwal2');
        insert con2;
        
        Training_Session__c ts=new Training_Session__c(Training_Topics__c='Page Layouts',Name='Test Training',RecordTypeId='012dM000003l5FRQAY');        
        insert ts;
        
        Attendee__c att=new Attendee__c(Email__c='abc@gmail.com',Training_Session__c= ts.id,Contact__c=con.Id);
        insert att;
        
        att.Contact__c=con2.Id;
        delete att;
    }

}